# Class assessment [Mohd Nizam Nasir Shaikh] {24198170}

In [1]:
#Q1-1
portfolios = [{"Client_id" : 1, "Asset_type" : "AAPL", "Value_usd" : 254.43, "is_high_risk" : True},
              {"Client_id" : 2, "Asset_type" : "MSFT", "Value_usd" : 509.23, "is_high_risk" : True},
              {"Client_id" : 3, "Asset_type" : "ETH", "Value_usd" : 3331.31, "is_high_risk" : False}]

In [2]:
portfolios

[{'Client_id': 1,
  'Asset_type': 'AAPL',
  'Value_usd': 254.43,
  'is_high_risk': True},
 {'Client_id': 2,
  'Asset_type': 'MSFT',
  'Value_usd': 509.23,
  'is_high_risk': True},
 {'Client_id': 3,
  'Asset_type': 'ETH',
  'Value_usd': 3331.31,
  'is_high_risk': False}]

In [3]:
#Q1.2 & 3 & 4
portfolios = [{"Client_id" : 1, "Asset_type" : "AAPL", "Value_usd" : 254.43, "is_high_risk" : True}, \
              {"Client_id" : 2, "Asset_type" : "MSFT", "Value_usd" : 509.23, "is_high_risk" : True}, \
              {"Client_id" : 3, "Asset_type" : "ETH", "Value_usd" : 3331.31, "is_high_risk" : False}]
for i in portfolios:
    if i["is_high_risk"]:
        new_value = i["Value_usd"]*0.90
        print(f"Client_id is {i["Client_id"]} and New_Calculated_Value {new_value:}")
    else:
        new_value = i["Value_usd"]*0.95
        print(f"Client_id is {i["Client_id"]} and New_Calculated_Value {new_value:}")

Client_id is 1 and New_Calculated_Value 228.98700000000002
Client_id is 2 and New_Calculated_Value 458.307
Client_id is 3 and New_Calculated_Value 3164.7445

In [4]:
#Q-2.1
import pandas as pd
df_SBC = pd.read_csv("stocks.csv")
df_SBC.head()

,Ticker,Date,Open,High,Low,Close,Adj Close,Volume
0,AAPL,07/02/2023,150.639999,155.229996,150.639999,154.649994,154.414230,83322600
1,MSFT,07/02/2023,260.529999,268.769989,260.079987,267.559998,266.891510,50841400
2,NFLX,07/02/2023,358.510010,364.179993,354.179993,362.950012,362.950012,6289400
3,GOOG,07/02/2023,103.629997,108.669998,103.547996,108.040001,108.040001,33738800
4,AAPL,08/02/2023,153.880005,154.580002,151.169998,151.919998,151.688400,64120100

In [5]:
df_SBC.columns

Index(['Ticker', 'Date', 'Open', 'High', 'Low', 'Close', 'Adj Close',
       'Volume'],
      dtype='object')

In [6]:
df_SBC.dtypes

Ticker        object
Date          object
Open         float64
High         float64
Low          float64
Close        float64
Adj Close    float64
Volume         int64
dtype: object

In [7]:
#Q-2.2
df_SBC.isnull().sum()

Ticker       0
Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [10]:
#Q-2.3
df_SBC["Date"] = pd.to_datetime(df_SBC["Date"], dayfirst=True)
df_SBC

,Ticker,Date,Open,High,Low,Close,Adj Close,Volume
0,AAPL,2023-02-07,150.639999,155.229996,150.639999,154.649994,154.414230,83322600
1,MSFT,2023-02-07,260.529999,268.769989,260.079987,267.559998,266.891510,50841400
2,NFLX,2023-02-07,358.510010,364.179993,354.179993,362.950012,362.950012,6289400
3,GOOG,2023-02-07,103.629997,108.669998,103.547996,108.040001,108.040001,33738800
4,AAPL,2023-02-08,153.880005,154.580002,151.169998,151.919998,151.688400,64120100
...,...,...,...,...,...,...,...,...
243,GOOG,2023-05-04,106.160004,106.300003,104.699997,105.209999,105.209999,19780600
244,AAPL,2023-05-05,170.979996,174.300003,170.759995,173.570007,173.570007,113316400
245,MSFT,2023-05-05,305.720001,311.970001,304.269989,310.649994,310.649994,28181200
246,NFLX,2023-05-05,323.609985,324.149994,319.440002,322.760010,322.760010,3988600
247,GOOG,2023-05-05,105.320000,106.440002,104.738998,106.214996,106.214996,20705300

In [12]:
#Q-3.1
df_SBC["Daily_Change"] = df_SBC["Close"] - df_SBC["Open"]
df_SBC

,Ticker,Date,Open,High,Low,Close,Adj Close,Volume,Daily_Change
0,AAPL,2023-02-07,150.639999,155.229996,150.639999,154.649994,154.414230,83322600,4.009995
1,MSFT,2023-02-07,260.529999,268.769989,260.079987,267.559998,266.891510,50841400,7.029999
2,NFLX,2023-02-07,358.510010,364.179993,354.179993,362.950012,362.950012,6289400,4.440002
3,GOOG,2023-02-07,103.629997,108.669998,103.547996,108.040001,108.040001,33738800,4.410004
4,AAPL,2023-02-08,153.880005,154.580002,151.169998,151.919998,151.688400,64120100,-1.960007
...,...,...,...,...,...,...,...,...,...
243,GOOG,2023-05-04,106.160004,106.300003,104.699997,105.209999,105.209999,19780600,-0.950005
244,AAPL,2023-05-05,170.979996,174.300003,170.759995,173.570007,173.570007,113316400,2.590012
245,MSFT,2023-05-05,305.720001,311.970001,304.269989,310.649994,310.649994,28181200,4.929993
246,NFLX,2023-05-05,323.609985,324.149994,319.440002,322.760010,322.760010,3988600,-0.849976
247,GOOG,2023-05-05,105.320000,106.440002,104.738998,106.214996,106.214996,20705300,0.894997

In [20]:
#Q-3.2
monthly_groupby = df_SBC.groupby(df_SBC["Date"].dt.month)[["Open","Close"]].mean()
print(monthly_groupby)

            Open       Close
Date
2     213.281234  212.745833
3     207.661956  208.217283
4     223.092171  223.444737
5     226.286999  225.605748

In [19]:
#Q-3.3
df_SBC

,Ticker,Date,Open,High,Low,Close,Adj Close,Volume,Daily_Change
0,AAPL,2023-02-07,150.639999,155.229996,150.639999,154.649994,154.414230,83322600,4.009995
1,MSFT,2023-02-07,260.529999,268.769989,260.079987,267.559998,266.891510,50841400,7.029999
2,NFLX,2023-02-07,358.510010,364.179993,354.179993,362.950012,362.950012,6289400,4.440002
3,GOOG,2023-02-07,103.629997,108.669998,103.547996,108.040001,108.040001,33738800,4.410004
4,AAPL,2023-02-08,153.880005,154.580002,151.169998,151.919998,151.688400,64120100,-1.960007
...,...,...,...,...,...,...,...,...,...
243,GOOG,2023-05-04,106.160004,106.300003,104.699997,105.209999,105.209999,19780600,-0.950005
244,AAPL,2023-05-05,170.979996,174.300003,170.759995,173.570007,173.570007,113316400,2.590012
245,MSFT,2023-05-05,305.720001,311.970001,304.269989,310.649994,310.649994,28181200,4.929993
246,NFLX,2023-05-05,323.609985,324.149994,319.440002,322.760010,322.760010,3988600,-0.849976
247,GOOG,2023-05-05,105.320000,106.440002,104.738998,106.214996,106.214996,20705300,0.894997