In [1]:
#Indexing Strings
Name = "Mohd Nizam"

In [2]:
Name[0:5]

'Mohd '

In [3]:
#Length of var = len()
len(Name)

10

In [4]:
#We can add string or int or floats by +
first = "mohd "
second = "nizam "
third = "nasir "
fourth = "shaikh"

In [5]:
Full_name = first+second+third+fourth
Full_name

'mohd nizam nasir shaikh'

In [6]:
#We can add initials too by adding indexing 
intials = first[0]+second[0]+third[0]
intials

'mnn'

#(in) and (not in) will check true or false if things are there in conditions or var or statement

In [7]:
# we can pick idx from 2 list
a = [[1,2,3], ['a','b','c']]

In [8]:
a[1][2]

'c'

In [9]:
niz = 1

In [10]:
niz + 4

5

In [11]:
niz * 3

3

In [12]:
# We have sorting - sorted(var) or sorted (var reverse = True/False)- ascending or descending order

In [13]:
# we can check the type by type() or we can also convert type for eq float(var) to int(var) or str

In [14]:
# we can do concatenation / + of types in correct way like 
a = 5.5
type(a)

float

In [15]:
b = "2.2"
type(b)

str

In [16]:
b + str(a)

'2.25.5'

In [17]:
a + float(b)

7.7

In [18]:
# Tuple , Dictionary & Sets

In [19]:
# if elif else statement
x = "nizam"
y = "mohd"
if x == "killer" :
        print("hello")
elif x == "bug" :
        print("world")
else:
    print("Run!!!")

Run!!!

In [20]:
age = 25
activity = "eat"

if age >= 26:
    if activity == "eat" : 
        print ("food menu")
    elif activity == "drink" :
        print("drink menu")
    else:
        print("Wrong place")
else:
    print("You are underaged")

You are underaged

c = "C"
count = 0
sentence = "Charlie"
count = 0
for c in sentence:
    if c == " ":
        count += 1
        total_words = count+1

even_nums = []
for i in range(5):
    if i%2 == 0:
        even_nums += [i]

In [21]:
list_nums = [1,2,3,4,5]

In [22]:
total = 6

In [23]:
for num in list_nums:
    total+=num

In [24]:
num

5

In [25]:
range(0,10)

range(0, 10)

In [26]:
list(range(0,15))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [27]:
odd_nums = []
for i in range(5):
    if i%1 == 0:
        odd_nums += [i]

In [28]:
odd_nums

[0, 1, 2, 3, 4]

In [29]:
L = [1,"N", 3 , [7,9,11]]

In [30]:
for i in range(len(L)):
    print(L[i])

1
N
3
[7, 9, 11]

In [31]:
x = 20
flag = 25
for i in range(2,x):
    if x%i == 0:
        flag= 40
        mult = i
        break

if flag == 30:
    print("%d is prime" %x)
else:
    print("%d is multiple of %d" %(mult, x))

2 is multiple of 20

In [32]:
#Input provides us to give an output as shown below
ownername= input("Enter the name : ")
ownervalue = input("enter the current value: ")

Enter the name :  Nizam
enter the current value:  9

In [33]:
#provides value in int or float as advised below
value_float = float(ownervalue)
shares_sale = int(input("How many share were sold: "))

How many share were sold:  100

In [34]:
# n- include new line f"Comments/Var: {}" - float .2f is 2 floating decimals, put {} curly bracket in curve brackets()
print(f"\n --- shares_sale ---")
print(f"name: {ownername}")
print(f"Total Cost: ${value_float * shares_sale: .2f}")

 --- shares_sale ---
name: Nizam
Total Cost: $ 900.00

In [35]:
asset_return = 0.04526
volatility = 0.1873

In [36]:
monthly_return = asset_return / 12
print(f"monthly return: {monthly_return: .6f}")

monthly return:  0.003772

In [37]:
#Continous data stored places by many decimals.
prices  = [150.50, 150.51, 150.515, 150.51512]
print(f"Max Price Fluctuation: {max(prices) - min(prices): .5f}")

Max Price Fluctuation:  0.01512

In [38]:
#Discrete data (Countable)
shares_owned = 100
transactions_today = 7
days_open = 252
print(f"Transaction per day: {transactions_today / days_open:.4f}")

Transaction per day: 0.0278

In [39]:
#Binary Data (Two-State)
is_default = False  #Boolean (True/False)
is_profitable = 2  #Integer 1/0 representation
if is_default:
    print("WARNING: Customer is in default.")
else:
    print("Customer is in good standing.")

Customer is in good standing.

In [40]:
#0 = Buy Signal , 1 = Sell Signal
labels = [0,0,1,1,0,0,1]
print(f"Total Buy Signals: {sum(labels)}")

Total Buy Signals: 3

In [41]:
#def is defining function
def times(a,b):
    product = a*b
    return product

In [42]:
#%product will define how 5*5
product = times(5,5)
"5 times 5 is %d" %product

'5 times 5 is 25'

In [43]:
# defining vowels in name 
def Count_Vowels(name):
    total = 0
    vowels = ['a','e','i','o','u']
    for i in name.lower():
        if i in vowels:
            total += 1
    return total

In [44]:
#defining percent of vowels
def Percent_Vowels(name) :
    num_vowels = Count_Vowels(name)
    percent = num_vowels/len(name)
    return percent

In [45]:
Percent_Vowels("aeiou")

1.0

In [46]:
# importing numpy has 2 types will does mean or mathematics algebra
import numpy as np
np.mean([1,2,3,4,5])

np.float64(3.0)

In [47]:
import numpy
numpy.mean([1,2,3])

np.float64(2.0)

In [48]:
# import os.getcwd gets us to import file path
import os
current_dir = os.getcwd()
current_dir

'C:\\Users\\Nizam\\Documents\\Programming for Financial Data Science'

In [49]:
# os.listdir will direct us slicing of files
contents = os.listdir()
print(contents[1:7])

['Assignment 1.ipynb', 'Assignment 1.pdf', 'Grades_Short.csv', 'Lab 2 questions.docx', 'Lecture 1.ipynb', 'Lecture 2.ipynb']

In [50]:
#importing panda name as short name [pd] and formula is pd.read_csv("file name")
import pandas as pd
df_sheet = pd.read_csv("Grades_Short.csv")

In [51]:
df_sheet

,Name,Previous_Part,Participation1,Min_Exam1,Min_Exam2,Participation2,Min_Exam3,Final,Grade
0,Student_1,NaN,4.644914,18.896109,12.251423,4.070390,2.053126,24.083518,NaN
1,Student_2,B,5.819681,6.803529,18.832506,2.345866,11.465733,18.530510,NaN
2,Student_3,D,NaN,7.332230,3.090670,0.736573,13.274000,17.008776,D
3,Student_4,NaN,8.171044,1.491651,17.197807,8.967996,1.901695,17.247879,A
4,Student_5,NaN,9.860791,12.025999,10.223933,NaN,14.208694,6.040760,A
...,...,...,...,...,...,...,...,...,...
95,Student_96,B,1.813924,14.169151,4.058973,9.164023,3.972431,29.483594,A
96,Student_97,NaN,9.866658,16.432005,13.015638,2.279279,7.951891,16.962208,D
97,Student_98,C,0.550869,5.728780,18.810710,5.894670,4.711678,2.768479,C
98,Student_99,NaN,NaN,19.406470,3.437905,0.033325,8.615252,15.444862,B
99,Student_100,C,5.412692,4.135261,8.599897,NaN,6.684029,24.142526,F

In [52]:
#.head() means 1 5 rows 
df_sheet.head(6)

,Name,Previous_Part,Participation1,Min_Exam1,Min_Exam2,Participation2,Min_Exam3,Final,Grade
0,Student_1,NaN,4.644914,18.896109,12.251423,4.070390,2.053126,24.083518,NaN
1,Student_2,B,5.819681,6.803529,18.832506,2.345866,11.465733,18.530510,NaN
2,Student_3,D,NaN,7.332230,3.090670,0.736573,13.274000,17.008776,D
3,Student_4,NaN,8.171044,1.491651,17.197807,8.967996,1.901695,17.247879,A
4,Student_5,NaN,9.860791,12.025999,10.223933,NaN,14.208694,6.040760,A
5,Student_6,C,6.740792,16.845551,18.543316,6.481176,19.868162,25.079405,D

In [53]:
#.tails() means last 5 rows
df_sheet.tail(5)

,Name,Previous_Part,Participation1,Min_Exam1,Min_Exam2,Participation2,Min_Exam3,Final,Grade
95,Student_96,B,1.813924,14.169151,4.058973,9.164023,3.972431,29.483594,A
96,Student_97,NaN,9.866658,16.432005,13.015638,2.279279,7.951891,16.962208,D
97,Student_98,C,0.550869,5.728780,18.810710,5.894670,4.711678,2.768479,C
98,Student_99,NaN,NaN,19.406470,3.437905,0.033325,8.615252,15.444862,B
99,Student_100,C,5.412692,4.135261,8.599897,NaN,6.684029,24.142526,F

In [54]:
# .shape advise us with how much no. of rows & columns 
df_sheet.shape

(100, 9)

In [55]:
# .dtypes advise us the data types of columns from file 
df_sheet.dtypes

Name               object
Previous_Part      object
Participation1    float64
Min_Exam1         float64
Min_Exam2         float64
Participation2    float64
Min_Exam3         float64
Final             float64
Grade              object
dtype: object

In [56]:
# .columns will give us all columns header names
df_sheet.columns

Index(['Name', 'Previous_Part', 'Participation1', 'Min_Exam1', 'Min_Exam2',
       'Participation2', 'Min_Exam3', 'Final', 'Grade'],
      dtype='object')

In [57]:
# .index will give us all rows header names
df_sheet.index

RangeIndex(start=0, stop=100, step=1)

In [58]:
# will get name column or any as [""] 
df_sheet["Name"]

0       Student_1
1       Student_2
2       Student_3
3       Student_4
4       Student_5
         ...
95     Student_96
96     Student_97
97     Student_98
98     Student_99
99    Student_100
Name: Name, Length: 100, dtype: object

In [59]:
# we can also have 2 columns by adding [[" "" "]]
df_sheet[["Name", "Final"]]

           Name      Final
0     Student_1  24.083518
1     Student_2  18.530510
2     Student_3  17.008776
3     Student_4  17.247879
4     Student_5   6.040760
..          ...        ...
95   Student_96  29.483594
96   Student_97  16.962208
97   Student_98   2.768479
98   Student_99  15.444862
99  Student_100  24.142526

[100 rows x 2 columns]

In [60]:
# we can store a var name for Name columns
names = df_sheet["Name"]
names

0       Student_1
1       Student_2
2       Student_3
3       Student_4
4       Student_5
         ...
95     Student_96
96     Student_97
97     Student_98
98     Student_99
99    Student_100
Name: Name, Length: 100, dtype: object

In [61]:
# setting var as rows_0 and .iloc[] finding details only from 1 rows  
rows_0 = df_sheet.iloc[0]
rows_0

Name              Student_1
Previous_Part           NaN
Participation1     4.644914
Min_Exam1         18.896109
Min_Exam2         12.251423
Participation2      4.07039
Min_Exam3          2.053126
Final             24.083518
Grade                   NaN
Name: 0, dtype: object

In [62]:
# shortcut without putting var name
df_sheet.iloc[0]

Name              Student_1
Previous_Part           NaN
Participation1     4.644914
Min_Exam1         18.896109
Min_Exam2         12.251423
Participation2      4.07039
Min_Exam3          2.053126
Final             24.083518
Grade                   NaN
Name: 0, dtype: object

In [63]:
# .iloc[ : ]  exclude last index or row no & .loc[ : ] will not exclude [ : ] its bracket slicing the nos it will give as below eq
df_sheet.loc[0:5]

,Name,Previous_Part,Participation1,Min_Exam1,Min_Exam2,Participation2,Min_Exam3,Final,Grade
0,Student_1,NaN,4.644914,18.896109,12.251423,4.070390,2.053126,24.083518,NaN
1,Student_2,B,5.819681,6.803529,18.832506,2.345866,11.465733,18.530510,NaN
2,Student_3,D,NaN,7.332230,3.090670,0.736573,13.274000,17.008776,D
3,Student_4,NaN,8.171044,1.491651,17.197807,8.967996,1.901695,17.247879,A
4,Student_5,NaN,9.860791,12.025999,10.223933,NaN,14.208694,6.040760,A
5,Student_6,C,6.740792,16.845551,18.543316,6.481176,19.868162,25.079405,D

In [64]:
# var[var["column name"] > / <] giving special changes if greater or less than for specific column
df_sheet[df_sheet["Final"] > 20]

,Name,Previous_Part,Participation1,Min_Exam1,Min_Exam2,Participation2,Min_Exam3,Final,Grade
0,Student_1,NaN,4.644914,18.896109,12.251423,4.070390,2.053126,24.083518,NaN
5,Student_6,C,6.740792,16.845551,18.543316,6.481176,19.868162,25.079405,D
9,Student_10,D,1.021157,3.139700,2.856374,NaN,0.061543,28.998119,A
11,Student_12,B,2.944178,9.528872,7.378003,NaN,4.209830,23.594192,NaN
12,Student_13,C,3.899183,1.412807,19.374800,1.385008,1.705823,20.357897,D
14,Student_15,NaN,1.646218,12.759581,0.173790,2.780132,19.832456,20.500686,F
16,Student_17,NaN,8.704634,11.772201,0.766820,NaN,6.584941,27.228106,A
21,Student_22,C,2.696191,2.849131,5.917214,2.031715,14.098999,25.159580,A
37,Student_38,B,7.490911,14.770992,1.929042,9.283878,0.822696,24.874065,C
38,Student_39,B,4.869348,NaN,NaN,7.249382,17.116687,27.546844,B
44,Student_45,C,9.275888,14.238669,12.611407,9.974223,18.538248,24.826121,NaN
45,Student_46,D,8.201331,5.335648,6.848789,NaN,15.735745,23.339117,D
46,Student_47,B,NaN,NaN,12.542168,8.268548,4.690654,28.844770,NaN
49,Student_50,C,7.377557,NaN,10.207855,NaN,7.735045,26.498426,F
52,Student_53,A,5.351784,15.253099,NaN,NaN,10.616918,23.991207,NaN
57,Student_58,NaN,8.079739,0.809952,2.629642,3.849146,10.405481,20.073388,A
60,Student_61,NaN,7.328905,2.968319,19.632805,8.036529,5.823609,29.137224,B
64,Student_65,NaN,4.852898,NaN,8.576893,NaN,10.512063,22.009133,NaN
69,Student_70,B,NaN,11.401637,14.141502,7.428173,14.835000,22.292931,NaN
71,Student_72,C,NaN,16.358824,19.983160,NaN,10.369708,28.367437,D
82,Student_83,A,0.612973,13.164297,3.401781,5.925625,4.814234,24.191423,B
90,Student_91,D,7.631834,5.208939,6.946794,8.113831,1.776112,25.891350,NaN
92,Student_93,D,3.343754,1.032350,0.263495,6.207145,10.384912,26.263845,F
94,Student_95,B,1.911885,NaN,19.061167,8.258303,1.888283,26.303140,NaN
95,Student_96,B,1.813924,14.169151,4.058973,9.164023,3.972431,29.483594,A
99,Student_100,C,5.412692,4.135261,8.599897,NaN,6.684029,24.142526,F

In [65]:
#slicing through index as usually given at 1 time var names = name column from table 
names[5]

'Student_6'

In [66]:
names[3:8]

3    Student_4
4    Student_5
5    Student_6
6    Student_7
7    Student_8
Name: Name, dtype: object

In [67]:
#slicing of what we want index as 1 2 4 by putting [[, , ]]
names[[1,2,4]]

1    Student_2
2    Student_3
4    Student_5
Name: Name, dtype: object

In [68]:
# .loc[0,:] picks out all columns with only 1 row
df_sheet.loc[0,:]

Name              Student_1
Previous_Part           NaN
Participation1     4.644914
Min_Exam1         18.896109
Min_Exam2         12.251423
Participation2      4.07039
Min_Exam3          2.053126
Final             24.083518
Grade                   NaN
Name: 0, dtype: object

In [69]:
# provide slicing of of rows & columns as only what we want .loc[rows:rows, "columns":"columns"] 
df_sheet.loc[1:3,"Name":"Min_Exam2"]

        Name Previous_Part  Participation1  Min_Exam1  Min_Exam2
1  Student_2             B        5.819681   6.803529  18.832506
2  Student_3             D             NaN   7.332230   3.090670
3  Student_4           NaN        8.171044   1.491651  17.197807

In [70]:
# .groupby("")[""].mean/.sum grouped data as by mean or sum 
grouped = df_sheet.groupby("Participation1")["Min_Exam3"].mean()
grouped

Participation1
0.130347     3.707453
0.360124    19.206236
0.472742     3.724755
0.488012     6.966196
0.550869     4.711678
              ...
9.275888    18.538248
9.550961    12.476877
9.843353    14.000997
9.860791    14.208694
9.866658     7.951891
Name: Min_Exam3, Length: 88, dtype: float64

In [71]:
# var["column"].apply(len) provide name rows as no and len of each rows
Name_Length = df_sheet["Name"].apply(len)
Name_Length

0      9
1      9
2      9
3      9
4      9
      ..
95    10
96    10
97    10
98    10
99    11
Name: Name, Length: 100, dtype: int64

In [72]:
# Filtering data from no of colums
df_sheet[df_sheet["Final"] > 25]

,Name,Previous_Part,Participation1,Min_Exam1,Min_Exam2,Participation2,Min_Exam3,Final,Grade
5,Student_6,C,6.740792,16.845551,18.543316,6.481176,19.868162,25.079405,D
9,Student_10,D,1.021157,3.139700,2.856374,NaN,0.061543,28.998119,A
16,Student_17,NaN,8.704634,11.772201,0.766820,NaN,6.584941,27.228106,A
21,Student_22,C,2.696191,2.849131,5.917214,2.031715,14.098999,25.159580,A
38,Student_39,B,4.869348,NaN,NaN,7.249382,17.116687,27.546844,B
46,Student_47,B,NaN,NaN,12.542168,8.268548,4.690654,28.844770,NaN
49,Student_50,C,7.377557,NaN,10.207855,NaN,7.735045,26.498426,F
60,Student_61,NaN,7.328905,2.968319,19.632805,8.036529,5.823609,29.137224,B
71,Student_72,C,NaN,16.358824,19.983160,NaN,10.369708,28.367437,D
90,Student_91,D,7.631834,5.208939,6.946794,8.113831,1.776112,25.891350,NaN
92,Student_93,D,3.343754,1.032350,0.263495,6.207145,10.384912,26.263845,F
94,Student_95,B,1.911885,NaN,19.061167,8.258303,1.888283,26.303140,NaN
95,Student_96,B,1.813924,14.169151,4.058973,9.164023,3.972431,29.483594,A

In [73]:
# filtering data as var[(var["column"] > val we can have both (&) (|) (var["column"] >)]
df_sheet[(df_sheet["Final"] > 25) & (df_sheet["Min_Exam3"] > 15)]

,Name,Previous_Part,Participation1,Min_Exam1,Min_Exam2,Participation2,Min_Exam3,Final,Grade
5,Student_6,C,6.740792,16.845551,18.543316,6.481176,19.868162,25.079405,D
38,Student_39,B,4.869348,NaN,NaN,7.249382,17.116687,27.546844,B

In [74]:
#var["column"].min/.max() will provide value
df_sheet["Min_Exam1"].max()

19.99783504019718

In [75]:
#var.column.mean() provide avg score
df_sheet.Final.mean()

np.float64(13.783110968861289)

In [76]:
#.describe will provide summary of data with numeric columns  
summary_df = df_sheet.describe()
summary_df

,Participation1,Min_Exam1,Min_Exam2,Participation2,Min_Exam3,Final
count,88.000000,90.000000,87.000000,73.000000,95.000000,96.000000
mean,4.743051,8.659125,9.771743,4.983830,8.906677,13.783111
std,2.807539,5.615365,6.122752,3.157272,5.652516,8.824519
min,0.130347,0.801646,0.173790,0.004253,0.061543,0.334204
25%,2.550494,4.175311,4.224489,2.017713,4.077882,6.613715
50%,4.394051,7.347127,8.120156,4.871176,7.951891,13.602305
75%,7.341068,13.387868,15.942719,8.036529,13.637498,20.393595
max,9.866658,19.997835,19.983160,9.974223,19.951910,29.483594

In [77]:
# adding var summary_df to get extract of some columns only  
summary_df[["Final", "Min_Exam3"]]

           Final  Min_Exam3
count  96.000000  95.000000
mean   13.783111   8.906677
std     8.824519   5.652516
min     0.334204   0.061543
25%     6.613715   4.077882
50%    13.602305   7.951891
75%    20.393595  13.637498
max    29.483594  19.951910

In [78]:
#var["column"].value_counts() count all the values of columns
counts = df_sheet["Grade"].value_counts()
counts

Grade
D    15
C    15
B    13
A    12
F    12
Name: count, dtype: int64

In [79]:
#adding var name as count to get only 1 value
counts["A"]

np.int64(12)

In [80]:
# .unique give values in array line with all the specific info
unique_values = df_sheet["Grade"].unique()
unique_values

array([nan, 'D', 'A', 'B', 'C', 'F'], dtype=object)

In [81]:
#adding var name as unique_values to get only 1 value 
unique_values[3]

'B'

In [82]:
#adding new column - var["Columns name which need to add"]
#var
df_sheet["Percentage"] = df_sheet["Final"]/36
df_sheet.head()

,Name,Previous_Part,Participation1,Min_Exam1,Min_Exam2,Participation2,Min_Exam3,Final,Grade,Percentage
0,Student_1,NaN,4.644914,18.896109,12.251423,4.070390,2.053126,24.083518,NaN,0.668987
1,Student_2,B,5.819681,6.803529,18.832506,2.345866,11.465733,18.530510,NaN,0.514736
2,Student_3,D,NaN,7.332230,3.090670,0.736573,13.274000,17.008776,D,0.472466
3,Student_4,NaN,8.171044,1.491651,17.197807,8.967996,1.901695,17.247879,A,0.479108
4,Student_5,NaN,9.860791,12.025999,10.223933,NaN,14.208694,6.040760,A,0.167799

In [83]:
#Deleting columns del(space) var{"Column name"]
del df_sheet["Percentage"]
df_sheet.head()

,Name,Previous_Part,Participation1,Min_Exam1,Min_Exam2,Participation2,Min_Exam3,Final,Grade
0,Student_1,NaN,4.644914,18.896109,12.251423,4.070390,2.053126,24.083518,NaN
1,Student_2,B,5.819681,6.803529,18.832506,2.345866,11.465733,18.530510,NaN
2,Student_3,D,NaN,7.332230,3.090670,0.736573,13.274000,17.008776,D
3,Student_4,NaN,8.171044,1.491651,17.197807,8.967996,1.901695,17.247879,A
4,Student_5,NaN,9.860791,12.025999,10.223933,NaN,14.208694,6.040760,A

In [84]:
df_sheet["Percentage"] = df_sheet["Final"]/36
df_sheet.head()

,Name,Previous_Part,Participation1,Min_Exam1,Min_Exam2,Participation2,Min_Exam3,Final,Grade,Percentage
0,Student_1,NaN,4.644914,18.896109,12.251423,4.070390,2.053126,24.083518,NaN,0.668987
1,Student_2,B,5.819681,6.803529,18.832506,2.345866,11.465733,18.530510,NaN,0.514736
2,Student_3,D,NaN,7.332230,3.090670,0.736573,13.274000,17.008776,D,0.472466
3,Student_4,NaN,8.171044,1.491651,17.197807,8.967996,1.901695,17.247879,A,0.479108
4,Student_5,NaN,9.860791,12.025999,10.223933,NaN,14.208694,6.040760,A,0.167799

In [85]:
#deleting multiple columns var.drop(["",""], axis=1 , inplace = True (axis=1 is column , axis=0 is row ,
#inplace = True it will appear inplace = False code will not appear 
df_sheet.drop(["Percentage","Previous_Part"], axis=1, inplace = True)
df_sheet.head()

,Name,Participation1,Min_Exam1,Min_Exam2,Participation2,Min_Exam3,Final,Grade
0,Student_1,4.644914,18.896109,12.251423,4.070390,2.053126,24.083518,NaN
1,Student_2,5.819681,6.803529,18.832506,2.345866,11.465733,18.530510,NaN
2,Student_3,NaN,7.332230,3.090670,0.736573,13.274000,17.008776,D
3,Student_4,8.171044,1.491651,17.197807,8.967996,1.901695,17.247879,A
4,Student_5,9.860791,12.025999,10.223933,NaN,14.208694,6.040760,A

In [90]:
#added new Issue date column with date time var[new col name] = "DDMMYY HH:MM"
df_sheet["Issue_Date"] = "20-10-2025 12:00"
df_sheet.head()

,Name,Participation1,Min_Exam1,Min_Exam2,Participation2,Min_Exam3,Final,Grade,Issue_Date
0,Student_1,4.644914,18.896109,12.251423,4.070390,2.053126,24.083518,NaN,20-10-2025 12:00
1,Student_2,5.819681,6.803529,18.832506,2.345866,11.465733,18.530510,NaN,20-10-2025 12:00
2,Student_3,NaN,7.332230,3.090670,0.736573,13.274000,17.008776,D,20-10-2025 12:00
3,Student_4,8.171044,1.491651,17.197807,8.967996,1.901695,17.247879,A,20-10-2025 12:00
4,Student_5,9.860791,12.025999,10.223933,NaN,14.208694,6.040760,A,20-10-2025 12:00

In [92]:
#var[new col] = pd.to_datetime(var["new col"]) pd.to_datetime formula
df_sheet["Issue_Date"] = pd.to_datetime(df_sheet["Issue_Date"])
df_sheet

,Name,Participation1,Min_Exam1,Min_Exam2,Participation2,Min_Exam3,Final,Grade,Issue_Date
0,Student_1,4.644914,18.896109,12.251423,4.070390,2.053126,24.083518,NaN,2025-10-20 12:00:00
1,Student_2,5.819681,6.803529,18.832506,2.345866,11.465733,18.530510,NaN,2025-10-20 12:00:00
2,Student_3,NaN,7.332230,3.090670,0.736573,13.274000,17.008776,D,2025-10-20 12:00:00
3,Student_4,8.171044,1.491651,17.197807,8.967996,1.901695,17.247879,A,2025-10-20 12:00:00
4,Student_5,9.860791,12.025999,10.223933,NaN,14.208694,6.040760,A,2025-10-20 12:00:00
...,...,...,...,...,...,...,...,...,...
95,Student_96,1.813924,14.169151,4.058973,9.164023,3.972431,29.483594,A,2025-10-20 12:00:00
96,Student_97,9.866658,16.432005,13.015638,2.279279,7.951891,16.962208,D,2025-10-20 12:00:00
97,Student_98,0.550869,5.728780,18.810710,5.894670,4.711678,2.768479,C,2025-10-20 12:00:00
98,Student_99,NaN,19.406470,3.437905,0.033325,8.615252,15.444862,B,2025-10-20 12:00:00
99,Student_100,5.412692,4.135261,8.599897,NaN,6.684029,24.142526,F,2025-10-20 12:00:00

In [95]:
#var locate 0 with 1 idx in date col
first_datetime = df_sheet.loc[0, "Issue_Date"]
first_datetime

Timestamp('2025-10-20 12:00:00')

In [96]:
#provide hour no
first_datetime.hour

12

In [97]:
first_datetime.dayofweek

0

In [101]:
first_datetime.is_leap_year

False

In [102]:
df_sheet.columns

Index(['Name', 'Participation1', 'Min_Exam1', 'Min_Exam2', 'Participation2',
       'Min_Exam3', 'Final', 'Grade', 'Issue_Date'],
      dtype='object')

In [104]:
# renaming columns of participants1 & 2 as One & Two with var.rename(col = {"old" : "New", "old" : "new"}, inplace = true will no give / False will give)
df_sheet.rename(columns = {"Participation1" : "ParticipantsOne" , "Participation2" : "ParticipantsTwo"}, inplace = False)

,Name,ParticipantsOne,Min_Exam1,Min_Exam2,ParticipantsTwo,Min_Exam3,Final,Grade,Issue_Date
0,Student_1,4.644914,18.896109,12.251423,4.070390,2.053126,24.083518,NaN,2025-10-20 12:00:00
1,Student_2,5.819681,6.803529,18.832506,2.345866,11.465733,18.530510,NaN,2025-10-20 12:00:00
2,Student_3,NaN,7.332230,3.090670,0.736573,13.274000,17.008776,D,2025-10-20 12:00:00
3,Student_4,8.171044,1.491651,17.197807,8.967996,1.901695,17.247879,A,2025-10-20 12:00:00
4,Student_5,9.860791,12.025999,10.223933,NaN,14.208694,6.040760,A,2025-10-20 12:00:00
...,...,...,...,...,...,...,...,...,...
95,Student_96,1.813924,14.169151,4.058973,9.164023,3.972431,29.483594,A,2025-10-20 12:00:00
96,Student_97,9.866658,16.432005,13.015638,2.279279,7.951891,16.962208,D,2025-10-20 12:00:00
97,Student_98,0.550869,5.728780,18.810710,5.894670,4.711678,2.768479,C,2025-10-20 12:00:00
98,Student_99,NaN,19.406470,3.437905,0.033325,8.615252,15.444862,B,2025-10-20 12:00:00
99,Student_100,5.412692,4.135261,8.599897,NaN,6.684029,24.142526,F,2025-10-20 12:00:00

In [114]:
df_grades = df_sheet["Grade"] 
df_grades

0     NaN
1     NaN
2       D
3       A
4       A
     ...
95      A
96      D
97      C
98      B
99      F
Name: Grade, Length: 200, dtype: object

In [ ]:
# concatinating Dataframes 
df_sheet = pd.concat([df_sheet_A,df_sheet_other], axis = 0)